{% set name = "sql-metadata" %}
{% set version = "2.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sql_metadata-{{ version }}.tar.gz
  sha256: 47fea2eba8f743554484be304fd4a865b57e52f45403ad8a7a217a3dcdfb26a0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python >=3.6,<4.0
  run:
    - python >=3.6,<4.0
    - sqlparse >=0.4.1,<0.5.0

test:
  imports:
    - sql_metadata
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/macbre/sql-metadata
  summary: Uses tokenized query returned by python-sqlparse and generates query metadata
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - OstapStefakQC
