{% set name = "sql-metadata" %}
{% set version = "2.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/sql_metadata-{{ version }}.tar.gz
  sha256: 2242603497bbcdb6e565c883df7b48eb85e19439acab54026a0e2b1cae6b5fe6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python {{ python_min }}
  run:
    - python >={{ python_min }},<4.0
    - sqlparse >=0.4.1,<0.5.0

test:
  imports:
    - sql_metadata
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/macbre/sql-metadata
  summary: Uses tokenized query returned by python-sqlparse and generates query metadata
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - timkpaine
    - OstapStefakQC
